### ISSUE TITLE
Question: Is time between onServiceRegistered and onServiceActive excessive

### ISSUE THREAD

**Issue by pandasys** [Zhuinden/simple-stack-compose-integration#14]
I have a screen whose model does quite a bit of processing and I was looking at ways to optimize the appearance of items in a LazyColumn. My solution involves chunking the results to get a fast initial view with further processing not affecting the UI since the items aren't visible. While I was experimenting I was also forming guidelines about what should occur in onServiceRegistered and onServiceActive, and then I ran into something unexpected. It regularly takes 300-400 millis between registration and activation.

I created a screen/model pair where the screen only displays a single line of text and the model only overrides the register/active function pairs -  add model in bindServices() and rememberService() first thing in ScreenComposable() On my personal device, Galaxy S10e, the time between registration and activation is consistently over 300 millis, which causes some UI glitches depending on where processing occurs.

Is this on my end somehow or is Simple Stack doing some very heavy lifting during this time. This duration forced me to move things into registration I might otherwise put in activation. As a side note, the time between deactivation and unregister is usually 1 milli or less. Thanks

**Comment by Zhuinden** [comment]
Simple-Stack itself is merely doing for loops and calling `onServiceRegistered()` and then eventually `onServiceActive()`, it definitely doesn't do anything complex enough on its own that it would take 300ms, as even calculating the activation chain is 1 for-loop over the explicit parent chain's services, which also isn't a lot.

`onServiceRegistered` is called for all models if their scope is created based on the history, so if `onServiceRegistered` is doing something *heavy* per say, I could see that causing slow-downs...

I somewhat recommend trying the CPU Profiler to see which exact call takes time. I wouldn't be surprised to see it be something like, ui model mapping for the LazyList done on the UI thread instead of on a computation scheduler (this is a common thing I've seen before).

I've also seen layout inflation in a RecyclerView take time because the views were complex, but that shouldn't be the case with Compose (even though I definitely see LazyList/SubcomposeLayout take.. uh, more time to render than usual)

**Comment by pandasys** [comment]
I have been profiling. Seems it's recomposition. Now I'm trying to see why. Thanks for your description. I've also been looking through the code. You've answered my question. Appreciate the library, thanks.
